GET http://localhost:3000/users/list HTTP/1.1
content-type: application/json
token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6IkFkbWluIiwicm9sZV9pZCI6MX0sImlhdCI6MTYyMjE2ODczNSwiZXhwIjoxNjIyMzQxNTM1fQ.i3dY3OpvNiCn5IJbIRB0JN02yOTFN41rwB_nRs1AAe0pG0mlDJzrrla2E1fflSr4wRbLy2rSl9B12emzTxWWwI2_aQ-09UZGTRmynnYNQmpL_ENWP1Po3Fnupc7WqaZEMfsyun18qLGIfIwa4IXFLJpFRL0xFwRoLGrhIOmT0EJmcL-aQYNwxgn2hSzet-qQVjv5h46UxEQo4DM1M7LJyKNjkEai4O7a5IxT8XdV5hKnJt5Zb9B_0IXL9oHSGxFeNzzdKUqOV3JS43eFHoqK3f_W4Ynk8Rp6DrpoNIYQR53NXqHkdRhNpTqpjp3yZ8sXGK_i0CmZPNyl7DzBIagf5w
