POST http://localhost:3000/users/session/logout HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6IkFkbWluIiwicm9sZV9pZCI6MX0sImlhdCI6MTYyMjE2NzU4NSwiZXhwIjoxNjIyMzQwMzg1fQ.NHtwyo7aDhmU3_JXEiLWrS0gVftnwAbPrGRR8cIVfvI1CKAwQ6qrFOgWxHWKPkyY-D1ON7IHuwl5Wr-0Q_cb3vV_w662GWbruwBL9swZ8YV0e0AzUN5tf55Lj8N12tfjQ8T8wg-EHcU4LiirUXTLx1TYNIZsBBffKpVk3-w4vmmxhBFho11auC_6PzjWODIiEjCb0x2tvchaxpNP5zm3VbWHenCgWU8WQYlDkeOaiqFL7QSi_jQZQeOak6jLECdUU6eweeUrkVNmYrvjqwIr2B1ibn3zBGyqDW06hNHPKgwOk9oQON8hjgfjsKbPVRGDfl6VGKBiwTotMaVkHcTVUg"
}
